set(SOURCES
	src/CC/AddAchievement.h
	src/CC/CC.cpp
	src/CC/CC.h
	src/CC/Clear.h
	src/CC/ClearAchievement.h
	src/CC/CrashToDesktop.h
	src/CC/Help.h
	src/EditorIDCache.h
	src/FormTypeMap.h
	src/PCH.h
	src/main.cpp
)
